import jsPDF from 'jspdf';
import Roboto from '../assets/Roboto.ttf'; 

export const generateTranscriptPDF = async (title: string, transcription: string[]): Promise<void> => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    try {
        const response = await fetch(Roboto);
        const buffer = await response.arrayBuffer();
        
        let binary = '';
        const bytes = new Uint8Array(buffer);
        for (let i = 0; i < bytes.byteLength; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        const base64Font = window.btoa(binary);

        doc.addFileToVFS("Roboto-Regular.ttf", base64Font);
        doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
    } catch (error) {
        console.error("Font cant loading:", error);
    }

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20; 
    const contentWidth = pageWidth - margin * 2;

    doc.setFillColor(234, 88, 12); 
    doc.rect(0, 0, pageWidth, 35, 'F'); 

    doc.setFont('Roboto', 'normal'); 
    doc.setFontSize(9);
    doc.setTextColor(255, 230, 200);
    const dateStr = new Date().toLocaleDateString('tr-TR', {
        year: 'numeric', month: 'long', day: 'numeric',
    });
    doc.text(dateStr, pageWidth - margin, 12, { align: 'right' });

    doc.setFont('Roboto', 'normal'); 
    doc.setFontSize(16); 
    doc.setTextColor(255, 255, 255);
    const safeTitle = title || 'YouTube Transcript';
    const titleLines = doc.splitTextToSize(safeTitle, contentWidth - 30); 
    doc.text(titleLines.slice(0, 2), margin, 22);

    doc.setFont('Roboto', 'normal'); 
    doc.setFontSize(11); 
    doc.setTextColor(45, 45, 45); 

    const fullText = transcription.join(' ').replace(/\s+/g, ' ');
    const sentences = fullText.match(/[^.!?]+[.!?]+/g) || [fullText];
    
    let paragraphs: string[] = [];
    let currentParagraph = "";
    
    sentences.forEach(sentence => {
        currentParagraph += sentence.trim() + " ";
        if (currentParagraph.length > 350) {
            paragraphs.push(currentParagraph.trim());
            currentParagraph = "";
        }
    });
    if (currentParagraph.trim()) paragraphs.push(currentParagraph.trim());

    let cursorY = 48; 
    const lineHeight = 6.5; 
    const paragraphSpacing = 4; 
    const footerHeight = 15;

    paragraphs.forEach((paragraph) => {
        const lines = doc.splitTextToSize(paragraph, contentWidth);

        lines.forEach((line: string) => {
            if (cursorY + lineHeight > pageHeight - footerHeight) {
                addFooter(doc, pageWidth, pageHeight, margin);
                doc.addPage();

                doc.setFillColor(234, 88, 12);
                doc.rect(0, 0, pageWidth, 5, 'F');
                cursorY = 20; 

                doc.setFont('Roboto', 'normal'); 
                doc.setFontSize(11);
                doc.setTextColor(45, 45, 45);
            }
            doc.text(line, margin, cursorY);
            cursorY += lineHeight;
        });
        
        cursorY += paragraphSpacing; 
    });

    addFooter(doc, pageWidth, pageHeight, margin);

    const fileName = `${safeTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}transcript.pdf`;
    doc.save(fileName);
};

function addFooter(doc: jsPDF, pageWidth: number, pageHeight: number, margin: number) {
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    
    doc.setFont('Roboto', 'normal'); 
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text('Generated by transcripTube', margin, pageHeight - 7);
    doc.text(`page ${(doc.internal as any).getCurrentPageInfo().pageNumber}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
}